name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: github.repository_owner == 'AchievedOwner'
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Bump versions
        uses: SiqiLu/dotnet-bump-version@2.1.0
        with:
            version_files: "./src/**/*.csproj"
            version_mask: 0.0.1.0
            version_overwrite: "*.*.*.${{ github.run_number }}"
      - name: Pack to publish
        id: pack
        run: |
          dotnet build -c release
          dotnet pack ./src/**/*.csproj -c release -o publish
